# Generated by Django 5.0.4 on 2025-01-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=200)),
                ('memory_verse', models.CharField(max_length=300)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('preacher', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sermons/')),
            ],
        ),
    ]
