# Generated by Django 5.0.4 on 2025-01-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-date'], 'verbose_name': 'School Lesson', 'verbose_name_plural': 'School Lessons'},
        ),
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['-date'], 'verbose_name': 'Sermon', 'verbose_name_plural': 'Sermons'},
        ),
        migrations.AlterField(
            model_name='school',
            name='content',
            field=models.TextField(verbose_name='Lesson Content'),
        ),
        migrations.AlterField(
            model_name='school',
            name='date',
            field=models.DateField(verbose_name='Date of Lesson'),
        ),
        migrations.AlterField(
            model_name='school',
            name='memory_verse',
            field=models.CharField(max_length=300, verbose_name='Memory Verse'),
        ),
        migrations.AlterField(
            model_name='school',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Lesson Title'),
        ),
        migrations.AlterField(
            model_name='school',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='Lesson Topic'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='sermons/', verbose_name='Audio File'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='content',
            field=models.TextField(verbose_name='Sermon Content'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='date',
            field=models.DateField(verbose_name='Date of Sermon'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='preacher',
            field=models.CharField(max_length=100, verbose_name="Preacher's Name"),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='theme',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sermon Theme'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sermon Title'),
        ),
    ]
