# Generated by Django 5.0.4 on 2025-01-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0002_alter_school_options_alter_sermon_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sermon',
        ),
    ]
