# Generated by Django 5.0.4 on 2025-01-10 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunday', '0003_delete_sermon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurtherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReflectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SundaySchoolLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('memory_verse', models.TextField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='lesson_banners/')),
            ],
        ),
        migrations.DeleteModel(
            name='school',
        ),
        migrations.AddField(
            model_name='reflectionquestion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sunday.sundayschoollesson'),
        ),
        migrations.AddField(
            model_name='lessonsection',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sunday.sundayschoollesson'),
        ),
        migrations.AddField(
            model_name='furtherreading',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='further_readings', to='sunday.sundayschoollesson'),
        ),
    ]
