# Generated by Django 5.0.4 on 2025-01-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonsection',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='reflectionquestion',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='FurtherReading',
        ),
        migrations.DeleteModel(
            name='LessonSection',
        ),
        migrations.DeleteModel(
            name='ReflectionQuestion',
        ),
        migrations.DeleteModel(
            name='SundaySchoolLesson',
        ),
    ]
