# Generated by Django 5.0.4 on 2025-01-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sermon', '0002_remove_lessonsection_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('memory_verse', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('further_reading', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sermons/audio/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='sermons/images/')),
            ],
        ),
    ]
