services:
  - type: web
    name: rcf
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn church.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DJANGO_SETTINGS_MODULE
        value: church.settings