# Generated by Django 5.0.4 on 2025-01-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
