# Generated by Django 5.0.4 on 2025-01-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcf', '0002_customuser_bio_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SundaySchoolLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sunday_school_images/')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
